### ISSUE TITLE
Is qbookfun.r script available in this repo?

### ISSUE THREAD

**Issue by jwang-lilly** [harrelfe/blogd#1]
Dear Professor Harrel,

Thanks so much for sharing your data analysis and reporting insight in the R workflow post.  qbookfun.r script is reference in the post and I wonder if this script is available in this or your other repos? No worries if it belongs to your private script collection.

**Comment by harrelfe** [comment]
`qbookfun` is for local use, and I am editing the script now to have less reliance on it.  Should you find that you need a function `qbookfun` I can give you access.  I use it mainly for a book.
